version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html
  php:
    image: php:7.0-fpm
    volumes:
      - ./www:/usr/share/nginx/html
    ports:
      - 9000
  php2:
    image: php:7.2-fpm
    volumes:
      - ./www:/usr/share/nginx/html
    ports:
      - 9000